name: Add Comment to Issue

on:
  workflow_dispatch:
    inputs:
      issue_number:
        description: 'Issue number to comment on'
        required: true
        default: '1'

permissions:
  issues: write
  contents: read

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Add comment to issue
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh api repos/billnapier/napier-test/issues/1/comments -f body='Hi from CLI'
          # gh issue comment ${{ github.event.inputs.issue_number }} --body "Hello world! This is an automated comment from a GitHub Action."
